const mongoose = require('mongoose');

const podcastSchema = mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  topic: {
    type: String,
    required: true,
  },
  host: {
    type: String,
    default: 'AI Host',
  },
  script: {
    type: String,
    // Script can be generated by AI
  },
  audioUrl: {
    type: String,
    // URL to the generated or uploaded audio file
  },
  platforms: {
    type: [String],
    enum: ['spotify', 'apple', 'youtube', 'google'],
    default: ['spotify'],
  },
  status: {
    type: String,
    enum: ['draft', 'scripted', 'recorded', 'scheduled', 'published', 'failed'],
    default: 'draft',
  },
  scheduledTime: {
    type: Date,
  },
  publishedAt: {
    type: Date,
  },
  duration: {
    type: Number, // in seconds
  },
  analytics: {
    totalDownloads: { type: Number, default: 0 },
    uniqueListeners: { type: Number, default: 0 },
    averageListenTime: { type: Number, default: 0 }, // percentage
    platformStats: {
      spotify: { downloads: { type: Number, default: 0 } },
      apple: { downloads: { type: Number, default: 0 } },
      youtube: { views: { type: Number, default: 0 } },
      google: { downloads: { type: Number, default: 0 } }
    }
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const Podcast = mongoose.model('Podcast', podcastSchema);

module.exports = Podcast;
